spring:
  sleuth:
    traceId128: true
    supportsJoin: false
  boot:
    message: "Hola Department Service"
  datasource:
    url: jdbc:mysql://localhost:3306/department_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: hola
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
loggin:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
