server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/department_db'
    username: root
    password: hola
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  boot:
    message: Hello from department service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
